CREATE DATABASE IF NOT EXISTS PUDIM_LANCHES;

USE PUDIM_LANCHES;

CREATE TABLE CADCLI(
    codcli INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomcli VARCHAR(100) NOT NULL,
    endcli VARCHAR(200) NOT NULL,
    telcli VARCHAR(15) NOT NULL
);

CREATE TABLE CADPRO(
    codpro INT NOT NULL PRIMARY KEY,
    despro VARCHAR(100) NOT NULL,
    vlrpro DECIMAL(10,2) NOT NULL
);

CREATE TABLE CADPED(
    codped INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    codcli INT NOT NULL,
    datped DATE NOT NULL,
    staped VARCHAR(1) NOT NULL,
    obsped VARCHAR(200),
    vlrped DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (codcli) REFERENCES CADCLI(codcli)
);

CREATE TABLE ITEPED(
    seqiteped INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    numite INT NOT NULL,
    codpro INT NOT NULL,
    qtdite INT NOT NULL,
    codped INT NOT NULL,
    FOREIGN KEY (codpro) REFERENCES CADPRO(codpro),
    FOREIGN KEY (codped) REFERENCES CADPED(codped),
    UNIQUE INDEX uk_iteped (numite, codpro)
);